version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./core/configs/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - web
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
#    volumes:
#      - static_volume:/app/staticfiles_root  
    command: ["python", "open_politics_project/manage.py", "runserver", "0.0.0.0:4000"]
    environment:
      - HUGGINGFACE_TOKEN=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
    networks:
      - web
    expose:
      - "4000"


networks:
  web:
    external: true
    
volumes:
  static_volume:
