services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    command: >
      sh -c "sleep 10 &&
            python open_politics_project/manage.py makemigrations &&
            python open_politics_project/manage.py migrate && 
            python open_politics_project/manage.py collectstatic --noinput &&
            python open_politics_project/manage.py runserver 0.0.0.0:4000"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - HUGGINGFACE_TOKEN
      - NEWS_API_KEY
      - OPENAI_API_KEY
      - IN_DOCKER
    networks:
      - web
    expose:
      - "4000"
    depends_on:
      - postgres
    volumes:
       - ./staticfiles_root:/app/staticfiles_root

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - web
    ports:
      - "5440:5432"
    expose:
      - "5440"

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - web
    expose:
      - "6379"

networks:
  web:
    external: true

volumes:
  postgres_data:
  redis_data:
