version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - .:/app
      - static_volume:/app/staticfiles_root  
    command: ["/app/start_server.sh"]
    environment:
      - DEBUG=True

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /var/www/letsencrypt:/var/www/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - web

volumes:
  static_volume:
