version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    #   - "8080:8080"  
    volumes:
      - .:/app
      - static_volume:/app/staticfiles_root  
    command: ["/app/start_server.sh"]
    environment:
      - DEBUG=True

  nginx:
    image: nginx:latest
    ports:
      - "80:80"       # Mapping the HTTP port
      - "8443:8443"     # Mapping the HTTPS port
    volumes:
      - ./nginx:/etc/nginx/conf.d            # Nginx configuration
      - /var/www/letsencrypt:/var/www/letsencrypt    # Letsencrypt challenges
      - /etc/letsencrypt:/etc/letsencrypt    # SSL certs
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - web

volumes:
  static_volume:
