version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
#    volumes:
#      - static_volume:/app/staticfiles_root  
    command: ["gunicorn", "open_politics_project.wsgi:application", "--bind", "0.0.0.0:4000", "--workers", "3"]
    networks:
      - web
    expose:
      - "4000"


networks:
  web:
    external: true
    
volumes:
  static_volume:
  
