apiVersion: v1
kind: Service
metadata:
  name: "open-politics-frontend"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: "open-politics-frontend"
