general:
  storageClass: standard
  imageTag: "latest"
  imageRepo: "registry.docker.io/openpoliticsproject/frontend"
  environment: "dev"
  branch: "my-feature-1"
application:
  frontendDomain: "open-politics.org"
  backendDomain: "api.open-politics.org"