apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "open-politics-backend"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://{{ .Values.application.frontendDomain }}"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-expose-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,access-control-allow-origin"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.application.backendDomain }}"
      secretName: "open-politics-backend-tls"
  rules:
    - host: "{{ .Values.application.backendDomain }}"
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: "open-politics-backend"
                port:
                  number: 80
