apiVersion: v1
kind: Secret
metadata:
  name: "first-superuser-password"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  password: "8t9ZBEJ3QcY5"
---
apiVersion: v1
kind: Secret
metadata:
  name: "secret-key"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  password: "4lQ1NmR5EL65" # Quick temporary fix for debugging because mittwald helm chart is down currently. THIS IS NOT SECURE!