apiVersion: v1
kind: Secret
metadata:
  name: "first-superuser-password"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-root-password"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-user-password"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: "secret-key"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque